ExpensesTracker.Web/ExpensesTracker.Web/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpensesTracker.Web.Data;
using ExpensesTracker.Web.Data.Entities;
using ExpensesTracker.Core.Services.Expenses;
using AutoMapper;
using ExpensesTracker.Web.ViewModels.Expenses;

namespace ExpensesTracker.Web.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly IMapper _mapper;

        public ExpensesController(IExpenseService expenseService, IMapper mapper)
        {
            _expenseService = expenseService
                ?? throw new ArgumentNullException(nameof(expenseService));
            this._mapper = mapper
                ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public IActionResult Index()
        {
            var expenses = this._expenseService.GetAllExpenses();
            var viewModels = this._mapper.Map<IEnumerable<AddExpenseViewModel>>(expenses);
            return this.View(viewModels);
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            return this.View();
        }


        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] ExpenseCreateModel InputModel)
        {
            if (!ModelState.IsValid) return this.View(InputModel);
            {
                var expense = this._mapper.Map<Expense>(InputModel);
                this._expenseService.Create(expense);

                return this.RedirectToAction(nameof(Index));
            }

        }

        [HttpGet("delete")]
        public IActionResult Delete(Guid id)
        {

            var expense = this._expenseService.GetById(id);
            if (expense is null) return this.NotFound();

            var viewModel = this._mapper.Map<AddExpenseViewModel>(expense);
            return this.View(viewModel);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            this._expenseService.Delete(id);


            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet("details")]
        public IActionResult Details(Guid id)
        {
            var expense = this._expenseService.GetOne(id);
            if (expense == null)
            {
                return this.NotFound();
            }
            var viewModel = this._mapper.Map<AddExpenseViewModel>(expense);
            return this.View(viewModel);
        }


        [HttpGet("edit")]
        public IActionResult Edit(Guid id)
        {
            var expense = this._expenseService.GetOneEdit(id);
            if (expense is null) return this.NotFound();

            var viewModel = this._mapper.Map<ExpenseEditModel>(expense);
            return View(viewModel);


        }


        [HttpPost("edit"),ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, AddExpenseViewModel inputModel)
        {
            if (!ModelState.IsValid) return this.View(inputModel);
            if (id != inputModel.Id) return this.NotFound();


            var expense = this._expenseService.GetById(id);
            if (expense is null) return this.NotFound();


            this._mapper.Map(inputModel, expense);
            this._expenseService.Update(expense);

            return this.RedirectToAction(nameof(Index));

        }
    }
}

ExpensesTracker.Web/ExpensesTracker.Web/Controllers/HomeController.cs
using ExpensesTracker.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExpensesTracker.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExpensesTracker.Web/ExpensesTracker.Web/Controllers/WorkersController.cs
using AutoMapper;
using ExpensesTracker.Core.Services.Expenses;
using ExpensesTracker.Core.Services.Workers;
using ExpensesTracker.Web.ViewModels.Expenses;
using ExpensesTracker.Web.ViewModels.Workers;
using Microsoft.AspNetCore.Mvc;

namespace ExpensesTracker.Web.Controllers
{
    public class WorkersController : Controller
    {
        private readonly IWorkerService _workerService;
        private readonly IMapper _mapper;

        public WorkersController(IWorkerService workerService, IMapper mapper)
        {
            _workerService = workerService
                ?? throw new ArgumentNullException(nameof(workerService));
            this._mapper = mapper
                ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var workers = this._workerService.GetAllWorkers();
            var viewModels = this._mapper.Map<IEnumerable<WorkerViewModel>>(workers);
            return this.View(viewModels);
        }
        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            var worker = this._workerService.GetById(id);
            if (worker is null) return this.NotFound();

            var viewModel = this._mapper.Map<WorkerViewModel>(worker);
            return this.View(viewModel);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            this._workerService.Delete(id);
            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Details(Guid id)
        {
            var worker = this._workerService.GetById(id);
            if (worker is null) return this.NotFound();

            var viewModel = this._mapper.Map<WorkerViewModel>(worker);
            return this.View(viewModel);
        }

    }
}

ExpensesTracker.Web/ExpensesTracker.Web/Views/Expenses/Create.cshtml
@model ExpenseCreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Expense</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ExpenseName" class="control-label"></label>
                <input asp-for="ExpenseName" class="form-control" />
                <span asp-validation-for="ExpenseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseDescription" class="control-label"></label>
                <input asp-for="ExpenseDescription" class="form-control" />
                <span asp-validation-for="ExpenseDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseAmount" class="control-label"></label>
                <input asp-for="ExpenseAmount" class="form-control" />
                <span asp-validation-for="ExpenseAmount" class="text-danger"></span>
            </div>
            <div class="dropdown">
                <label class="form-label" asp-for="ExpenseType">Period:</label>
                <select class="dropbtn" asp-for="ExpenseType">
                    <option value="">Select Period</option>
                    <option value="Daily">Daily</option>
                    <option value="Monthly">Monthly</option>
                    <option value="Yearly">Yearly</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpensesTracker.Web/ExpensesTracker.Web/Views/Expenses/Delete.cshtml
@model AddExpenseViewModel

@{
	ViewData["Title"] = "Delete";
}
@if (Model is null)
{
	<p>No expense was found with this Id</p>
}
else
{


	<h1>Delete</h1>

	<h3>Are you sure you want to delete this?</h3>
	<div>
		<h4>Expense</h4>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.ExpenseName)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.ExpenseName)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.ExpenseDescription)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.ExpenseDescription)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.ExpenseType)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.ExpenseType)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.ExpenseAmount)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.ExpenseAmount)
			</dd>
		</dl>

		<form asp-action="Delete">
			<input type="hidden" asp-for="Id" />
			<input type="submit" value="Delete" class="btn btn-danger" />
			<a asp-action="Index">Back to List</a>
		</form>
		|

	</div>
}

ExpensesTracker.Web/ExpensesTracker.Web/Views/Expenses/Details.cshtml
@model AddExpenseViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseAmount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a asp-action="Index">Back to List</a>
</div>

ExpensesTracker.Web/ExpensesTracker.Web/Views/Expenses/Edit.cshtml
@model ExpenseEditModel

@{
	ViewData["Title"] = "Edit";
}
@if (Model is null)

{
	<p>No expense was found with this Id</p>
}
else
{

	<h1>Edit</h1>

	<h4>Expense</h4>
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="Id"/>
				<div class="form-group">
					<label asp-for="ExpenseName" class="control-label"></label>
					<input asp-for="ExpenseName" class="form-control" />
					<span asp-validation-for="ExpenseName" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="ExpenseDescription" class="control-label"></label>
					<input asp-for="ExpenseDescription" class="form-control" />
					<span asp-validation-for="ExpenseDescription" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="ExpenseAmount" class="control-label"></label>
					<input asp-for="ExpenseAmount" class="form-control" />
					<span asp-validation-for="ExpenseAmount" class="text-danger"></span>
				</div>
				<div class="dropdown">
					<label class="form-label" asp-for="ExpenseType">Period:</label>
					<select class="dropbtn" asp-for="ExpenseType">
						<option value="">Select Period</option>
						<option value="Daily">Daily</option>
						<option value="Monthly">Monthly</option>
						<option value="Yearly">Yearly</option>
					</select>
				</div>
				<div class="form-group">
					<input type="submit" value="Save" class="btn btn-primary" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-action="Index">Back to List</a>
	</div>

	@section Scripts {
	@{
			await Html.RenderPartialAsync("_ValidationScriptsPartial");
		}
	}
}

ExpensesTracker.Web/ExpensesTracker.Web/Views/Expenses/Index.cshtml
@model IEnumerable<AddExpenseViewModel>

@{
    ViewData["Title"] = "Expenses";
}

<h1>Expenses</h1>

<p>
    <a id="createButton" asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseAmount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var viewModel in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => viewModel.ExpenseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => viewModel.ExpenseDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => viewModel.ExpenseType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => viewModel.ExpenseAmount)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@viewModel.Id"class="btn btn-primary">Edit</a> |
                <a asp-action="Details" asp-route-id="@viewModel.Id"class="btn btn-primary">Details</a> |
                <a asp-action="Delete" asp-route-id="@viewModel.Id"class=" btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ExpensesTracker.Web/ExpensesTracker.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4"><strong>WELCOME TO PES BANK</strong></h1>
    <hr></hr>
    <p>The most reliable bank</p>
</div>

<div class=" text-left">
    <h2>About us:</h2>
    <div class="about-container">
        <div class="person">
            <h3>Petromil Sirakov</h3>
            <div class="info">
                <p>I am Petromil Draganov Sirakov, I have big goals of becoming a fully realized developer and I can only achieve these goals with hard work!</p>
            </div>
        </div>
        <div class="person">
            <h3>Enis Kasper</h3>
            <div class="info">
                <p>I am Enis Beycan Kasper, I am ambitious, motivated to work, polite, communicative, I want to become a good developer, who does his job with pleasure.</p>
            </div>
        </div>
        <div class="person">
            <h3>Stefan Stefanov</h3>
            <div class="info">
                <p>I am Stefan Georgiev Stefanov, a beginner programmer with a lot of different goals! By becoming a real programmer I want to achieve these goals and make myself known in the IT sphere.</p>
            </div>
        </div>
    </div>

ExpensesTracker.Web/ExpensesTracker.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PES Bank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpensesTracker.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PES Bank</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="Index">Workers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExpensesTracker.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExpensesTracker.Web/ExpensesTracker.Web/Views/Workers/Delete.cshtml
@model WorkerViewModel

@{
	ViewData["Title"] = "Delete";
}
@if (Model is null)
{
	<p>No worker was found with this Id</p>
}
else
{


	<h1>Delete</h1>

	<h3>Are you sure you want to delete this?</h3>
	<div>
		<h4>Workers</h4>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Name)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Name)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.LastName)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.LastName)
			</dd>
			<dt class="col-sm-2">
				<p>PIN</p>
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.PesonalIndentificationNumber)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.DateOfBirth)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.DateOfBirth)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Position)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Position)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.PhoneNumber)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.PhoneNumber)
			</dd>
		</dl>

		<form asp-action="DeleteConfirmed">
			<input type="hidden" asp-for="Id" />
			<input type="submit" value="Delete" class="btn btn-danger" />
			<a asp-action="Index">Back to List</a>
		</form>


	</div>
}

ExpensesTracker.Web/ExpensesTracker.Web/Views/Workers/Details.cshtml
@model WorkerViewModel

@{
    ViewData["Title"] = "Details";
}
@if (Model is null)
{
    <p>No worker was found with this Id</p>
}
else
{


    <h1>Details</h1>
    <div>
        <h4>Workers</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                <p>PIN</p>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PesonalIndentificationNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DateOfBirth)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Position)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Position)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
        </dl>

            <a class ="btn btn-primary" asp-action="Index">Back to List</a>
    </div>
}

ExpensesTracker.Web/ExpensesTracker.Web/Views/Workers/Index.cshtml
@model IEnumerable<WorkerViewModel>

@{
    ViewData["Title"] = "Workers";
}

<h1>Workers</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var viewModel in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => viewModel.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => viewModel.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => viewModel.Position)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => viewModel.PhoneNumber)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@viewModel.Id" class="btn btn-primary">Details</a>
                    <a asp-action="Delete" asp-route-id="@viewModel.Id" class=" btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>